api_version: 1

train_batch_size: 32
val_batch_size: 32
num_workers: 16
input_size: 384
backbone: swin_large_patch4_window12_384
augmentation_func: peko.augmentation.get_augv5

total_epochs: 10
train_dataset: hotels50k_s1024
n_classes: 38768

model:
  fqdn: peko.torch.swinarcface.SwinTransformerEncoderArcfaceModel
  kwargs:
    n_classes: 38768
    model_name: swin_large_patch4_window12_384
    pretrained: true
    margin: 0.25
    scale: 30

pretrained_model: null
pretrained_remove_fc: null

optimizer:
  fqdn: torch.optim.AdamW
  kwargs:
    lr: 0.0001

scheduler:
  fqdn: torch.optim.lr_scheduler.CosineAnnealingLR
  kwargs:
    T_max: 1
    eta_min: 0.000001

eval_dataset:
  - hotels50k_s1024
  - hotelid
